<a href="https://colab.research.google.com/github/ishnt/Data_science_stuff/blob/main/Iris_Prediction_using_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression Implementation

In [15]:
from sklearn.datasets import load_iris

In [16]:
dataset=load_iris()

In [17]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [18]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [19]:
import pandas as pd
import numpy as np

In [20]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [21]:
df['target']=dataset.target

In [22]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [23]:
df_copy=df[df['target']!=2]


In [24]:
df_copy['target'].unique()

array([0, 1])

In [25]:
df_copy.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [28]:
#independent and dependent feature
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
classification=LogisticRegression()

In [34]:
classification.fit(x_train,y_train)

LogisticRegression()

In [35]:
classification.predict(x_train)

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1])

In [36]:
y_train

55    1
88    1
26    0
42    0
69    1
     ..
60    1
71    1
14    0
92    1
51    1
Name: target, Length: 80, dtype: int64

In [37]:
y_pred=classification.predict(x_test)

## Confusion Metrics,Accuracy,Classification Report

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [40]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [41]:
print(accuracy_score(y_test,y_pred))

1.0


In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



Cross Validation

In [43]:
from sklearn.model_selection import KFold

In [45]:
cv=KFold(n_splits=5)

In [46]:
print(cv)

KFold(n_splits=5, random_state=None, shuffle=False)


In [47]:
from sklearn.model_selection import cross_val_score

In [50]:
## these are the scores all the cross validation
scores=cross_val_score(classification,x_train,y_train,cv=5)

In [51]:
scores

array([1., 1., 1., 1., 1.])

In [56]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
x, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [57]:
model=LogisticRegression()

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [62]:
model.fit(x_train,y_train)

LogisticRegression()

In [64]:
y_pred=model.predict(x_test)

In [65]:

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [66]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(classification,x_train,y_train,cv=5)

In [68]:
np.mean(scores)

0.8087500000000001