<a href="https://colab.research.google.com/github/ishnt/Data_science_stuff/blob/main/rnn_with_embedding_layer_and_stacked_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np

In [75]:
docs = [
    "The quick brown fox jumps over the lazy dog.",
    "Python is a versatile programming language.",
    "Today is a beautiful day.",
    "I enjoy learning new things.",
    "The sky is clear and the sun is shining.",
    "Coding is both challenging and rewarding.",
    "Reading books opens up new worlds.",
    "Practice makes perfect.",
    "Nature provides us with endless beauty.",
    "Innovation drives progress in technology."
]

In [76]:
import tensorflow as tf
from keras.preprocessing.text import Tokenizer

tokenizer=Tokenizer(oov_token='<nothing>')

In [77]:
tokenizer.fit_on_texts(docs)

In [78]:
tokenizer.word_index

{'<nothing>': 1,
 'is': 2,
 'the': 3,
 'a': 4,
 'new': 5,
 'and': 6,
 'quick': 7,
 'brown': 8,
 'fox': 9,
 'jumps': 10,
 'over': 11,
 'lazy': 12,
 'dog': 13,
 'python': 14,
 'versatile': 15,
 'programming': 16,
 'language': 17,
 'today': 18,
 'beautiful': 19,
 'day': 20,
 'i': 21,
 'enjoy': 22,
 'learning': 23,
 'things': 24,
 'sky': 25,
 'clear': 26,
 'sun': 27,
 'shining': 28,
 'coding': 29,
 'both': 30,
 'challenging': 31,
 'rewarding': 32,
 'reading': 33,
 'books': 34,
 'opens': 35,
 'up': 36,
 'worlds': 37,
 'practice': 38,
 'makes': 39,
 'perfect': 40,
 'nature': 41,
 'provides': 42,
 'us': 43,
 'with': 44,
 'endless': 45,
 'beauty': 46,
 'innovation': 47,
 'drives': 48,
 'progress': 49,
 'in': 50,
 'technology': 51}

In [79]:
tokenizer.word_counts

OrderedDict([('the', 4),
             ('quick', 1),
             ('brown', 1),
             ('fox', 1),
             ('jumps', 1),
             ('over', 1),
             ('lazy', 1),
             ('dog', 1),
             ('python', 1),
             ('is', 5),
             ('a', 2),
             ('versatile', 1),
             ('programming', 1),
             ('language', 1),
             ('today', 1),
             ('beautiful', 1),
             ('day', 1),
             ('i', 1),
             ('enjoy', 1),
             ('learning', 1),
             ('new', 2),
             ('things', 1),
             ('sky', 1),
             ('clear', 1),
             ('and', 2),
             ('sun', 1),
             ('shining', 1),
             ('coding', 1),
             ('both', 1),
             ('challenging', 1),
             ('rewarding', 1),
             ('reading', 1),
             ('books', 1),
             ('opens', 1),
             ('up', 1),
             ('worlds', 1),
             ('practice

In [80]:
tokenizer.document_count

10

In [81]:
sequences=tokenizer.texts_to_sequences(docs)

In [82]:
from keras.utils import pad_sequences
nsequences=pad_sequences(sequences,maxlen=10,padding='post')

In [83]:
nsequences

array([[ 3,  7,  8,  9, 10, 11,  3, 12, 13,  0],
       [14,  2,  4, 15, 16, 17,  0,  0,  0,  0],
       [18,  2,  4, 19, 20,  0,  0,  0,  0,  0],
       [21, 22, 23,  5, 24,  0,  0,  0,  0,  0],
       [ 3, 25,  2, 26,  6,  3, 27,  2, 28,  0],
       [29,  2, 30, 31,  6, 32,  0,  0,  0,  0],
       [33, 34, 35, 36,  5, 37,  0,  0,  0,  0],
       [38, 39, 40,  0,  0,  0,  0,  0,  0,  0],
       [41, 42, 43, 44, 45, 46,  0,  0,  0,  0],
       [47, 48, 49, 50, 51,  0,  0,  0,  0,  0]], dtype=int32)

In [84]:
#setiment analysis using rnn
from keras.datasets import imdb
imdb.load_data( num_words=10000)

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 194, 1153, 194, 8255, 78, 

In [85]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [86]:
(x_train , y_train)  , (x_test , y_test)= imdb.load_data(  num_words=10000)

In [87]:
print(len(x_train[0]))

218


In [88]:
print(len(x_train[1]))

189


In [89]:
from keras.utils import pad_sequences
x_train=pad_sequences(x_train,maxlen=50,padding='post')
x_test=pad_sequences(x_test,maxlen=50,padding='post')

In [90]:
print(x_train)

[[2071   56   26 ...   19  178   32]
 [8255    5    2 ...   16  145   95]
 [ 215   28  610 ...    7  129  113]
 ...
 [   4   65  496 ...    4 3586    2]
 [  13   18   31 ...   12    9   23]
 [7585    8 2197 ...  204  131    9]]


In [91]:
print(x_test)

[[ 394  354    4 ...   14    6  717]
 [   5   45  252 ...  125    4 3077]
 [   7 2460    2 ...    9   57  975]
 ...
 [2515  395 4257 ...   21  846 5518]
 [  78  232   15 ... 2302    7  470]
 [   9   57   65 ...   34 2005 2643]]


In [92]:
print(x_test[0])

[ 394  354    4  123    9 1035 1035 1035   10   10   13   92  124   89
  488 7944  100   28 1668   14   31   23   27 7479   29  220  468    8
  124   14  286  170    8  157   46    5   27  239   16  179    2   38
   32   25 7944  451  202   14    6  717]


In [93]:
print(len(x_test[0]))

50


In [94]:
print(len(x_test[90]))

50


In [95]:
model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 2, input_length = 50))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=False))
model.add(Dense(1,activation = 'sigmoid'))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_7 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_7 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [96]:
model.compile(metrics = ['acc'], optimizer = 'adam', loss = 'binary_crossentropy')

In [97]:
model.fit(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))

Epoch 1/5
782/782 [==============================] - 14s 15ms/step - loss: 0.6236 - acc: 0.6140 - val_loss: 0.4440 - val_acc: 0.7966
Epoch 2/5
782/782 [==============================] - 11s 14ms/step - loss: 0.3995 - acc: 0.8235 - val_loss: 0.4101 - val_acc: 0.8147
Epoch 3/5
782/782 [==============================] - 12s 15ms/step - loss: 0.3284 - acc: 0.8636 - val_loss: 0.4201 - val_acc: 0.8133
Epoch 4/5
782/782 [==============================] - 12s 15ms/step - loss: 0.2916 - acc: 0.8848 - val_loss: 0.4585 - val_acc: 0.8057
Epoch 5/5
782/782 [==============================] - 13s 17ms/step - loss: 0.2639 - acc: 0.8987 - val_loss: 0.4682 - val_acc: 0.7989


In [98]:
test_data = x_test[0][0:50].reshape(1,-1)

In [101]:
if model.predict(test_data) < 0.5:
  print('negative review')
else:
  print('positive review')

1/1 [==============================] - 0s 35ms/step
negative review


In [103]:
#stacked rnn
model1 = Sequential()
model1.add(SimpleRNN(20, input_shape = (50,1), return_sequences=True))
model1.add(SimpleRNN(32, input_shape = (50,1), return_sequences=False))
model1.add(Dense(1,activation = 'sigmoid'))

model1.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_10 (SimpleRNN)   (None, 50, 20)            440       
                                                                 
 simple_rnn_11 (SimpleRNN)   (None, 32)                1696      
                                                                 
 dense_9 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2169 (8.47 KB)
Trainable params: 2169 (8.47 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [104]:
model1.compile(metrics = ['acc'], optimizer = 'adam', loss = 'binary_crossentropy')

In [105]:
model1.fit(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))

Epoch 1/5
782/782 [==============================] - 22s 25ms/step - loss: 0.6970 - acc: 0.4995 - val_loss: 0.6961 - val_acc: 0.5025
Epoch 2/5
782/782 [==============================] - 17s 22ms/step - loss: 0.6945 - acc: 0.5073 - val_loss: 0.6937 - val_acc: 0.5065
Epoch 3/5
782/782 [==============================] - 19s 24ms/step - loss: 0.6935 - acc: 0.5122 - val_loss: 0.6942 - val_acc: 0.5089
Epoch 4/5
782/782 [==============================] - 20s 25ms/step - loss: 0.6931 - acc: 0.5144 - val_loss: 0.6936 - val_acc: 0.5188
Epoch 5/5
782/782 [==============================] - 19s 25ms/step - loss: 0.6931 - acc: 0.5076 - val_loss: 0.6933 - val_acc: 0.5181


In [112]:
if model.predict(test_data) < 0.5:
  print('negative review')
else:
  print('positive review')

1/1 [==============================] - 0s 72ms/step
negative review
