<a href="https://colab.research.google.com/github/ishnt/Data_science_stuff/blob/main/Support_Vector_Classifier_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
## Lets create synthetic data points
from sklearn.datasets import make_classification

In [ ]:
x,y=make_classification(n_samples=1000,n_features=2,n_classes=2,
                        n_clusters_per_class=2,n_redundant=0)

In [ ]:
x

array([[ 0.8466266 , -1.33717932],
       [ 0.26770577, -0.9384214 ],
       [-0.44442411,  1.17357737],
       ...,
       [-0.92526052, -0.82152234],
       [ 0.07392147,  2.05743689],
       [-1.63922221,  1.17758822]])

In [ ]:
y

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,

In [ ]:
sns.scatterplot(x=pd.DataFrame(x)[0],y=pd.DataFrame(x)[1],hue=y)

<Axes: xlabel='0', ylabel='1'>

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=10)

In [ ]:
x_train

array([[ 0.73178472, -0.23041496],
       [-0.99171221,  1.87214237],
       [ 0.54673905, -1.138643  ],
       ...,
       [-3.73318609,  1.2999376 ],
       [ 0.10605187, -0.98761161],
       [ 0.11926188,  1.14551452]])

In [ ]:
x_test

array([[-0.97954629, -0.78885839],
       [ 1.60758272, -0.44814378],
       [-1.05075665, -0.78998318],
       [ 1.75055145,  2.12524428],
       [ 0.89644886,  1.99971426],
       [-0.79369499,  0.78109472],
       [-0.10062081, -2.05063736],
       [ 1.99543444, -0.46409736],
       [ 1.55744401,  1.14700064],
       [-0.28813717,  1.11856   ],
       [-0.96759284, -0.32036118],
       [ 0.91057595,  0.96976887],
       [ 0.38884035,  0.48934031],
       [ 1.10266059,  1.9156096 ],
       [ 0.63421117, -1.14831234],
       [-0.92915272, -0.602164  ],
       [ 1.41276301, -0.65538945],
       [-2.14371105,  1.61362976],
       [-0.62394833, -0.24553287],
       [-0.79919881,  0.89434078],
       [-1.33159403,  1.10599927],
       [-1.84056662,  1.07169514],
       [ 1.14276711,  0.19249612],
       [ 1.64582515,  1.18418896],
       [-1.05068225, -0.53012518],
       [-0.70744841,  0.964808  ],
       [-1.28139521, -1.20403428],
       [ 1.04590952, -1.12411437],
       [ 0.61769175,

In [ ]:
from sklearn.svm import SVC
svm=SVC(kernel='linear')

In [ ]:
svm.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred=svm.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.95      0.94       110
           1       0.96      0.94      0.95       140

    accuracy                           0.94       250
   macro avg       0.94      0.95      0.94       250
weighted avg       0.94      0.94      0.94       250

[[105   5]
 [  9 131]]
0.944


In [ ]:
#hyperparameter tuning
from sklearn.model_selection import GridSearchCV

parameters= {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':['linear']
              }


In [ ]:
cfg=GridSearchCV(SVC(),param_grid=parameters,refit=True,cv=5,verbose=3)

In [ ]:
cfg.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.953 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.953 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.953 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.940 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.940 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.953 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.953 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.953 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.940 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.940 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.953 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [ ]:
cfg.best_estimator_

SVC(C=0.1, gamma=1, kernel='linear')

In [ ]:
cfg.best_score_

0.9480000000000001

In [ ]:
cfg.best_params_

{'C': 0.1, 'gamma': 1, 'kernel': 'linear'}

In [ ]:
classifier=SVC(C= 0.1, gamma= 1, kernel= 'linear')

In [ ]:
classifier.fit(x_train,y_train)

SVC(C=0.1, gamma=1, kernel='linear')

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.95      0.94       110
           1       0.96      0.94      0.95       140

    accuracy                           0.94       250
   macro avg       0.94      0.95      0.94       250
weighted avg       0.94      0.94      0.94       250

[[105   5]
 [  9 131]]
0.944
