<a href="https://colab.research.google.com/github/ishnt/Data_science_stuff/blob/main/WORD2VEC_USING_SPACY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
pip install -U spacy

In [33]:
!python -m spacy download en_core_web_md
import spacy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 9.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [34]:
nlp = spacy.load("en_core_web_md")

In [35]:
doc=nlp("dog cat banana fdfafa")

In [36]:
for token in doc:
  print(token.text,"vector:",token.has_vector,"OOV:",token.is_oov)

dog vector: True OOV: False
cat vector: True OOV: False
banana vector: True OOV: False
fdfafa vector: False OOV: True


In [37]:
doc[0].vector


array([ 1.2330e+00,  4.2963e+00, -7.9738e+00, -1.0121e+01,  1.8207e+00,
        1.4098e+00, -4.5180e+00, -5.2261e+00, -2.9157e-01,  9.5234e-01,
        6.9880e+00,  5.0637e+00, -5.5726e-03,  3.3395e+00,  6.4596e+00,
       -6.3742e+00,  3.9045e-02, -3.9855e+00,  1.2085e+00, -1.3186e+00,
       -4.8886e+00,  3.7066e+00, -2.8281e+00, -3.5447e+00,  7.6888e-01,
        1.5016e+00, -4.3632e+00,  8.6480e+00, -5.9286e+00, -1.3055e+00,
        8.3870e-01,  9.0137e-01, -1.7843e+00, -1.0148e+00,  2.7300e+00,
       -6.9039e+00,  8.0413e-01,  7.4880e+00,  6.1078e+00, -4.2130e+00,
       -1.5384e-01, -5.4995e+00,  1.0896e+01,  3.9278e+00, -1.3601e-01,
        7.7732e-02,  3.2218e+00, -5.8777e+00,  6.1359e-01, -2.4287e+00,
        6.2820e+00,  1.3461e+01,  4.3236e+00,  2.4266e+00, -2.6512e+00,
        1.1577e+00,  5.0848e+00, -1.7058e+00,  3.3824e+00,  3.2850e+00,
        1.0969e+00, -8.3711e+00, -1.5554e+00,  2.0296e+00, -2.6796e+00,
       -6.9195e+00, -2.3386e+00, -1.9916e+00, -3.0450e+00,  2.48

In [38]:
doc[1].vector

array([ 3.7032e+00,  4.1982e+00, -5.0002e+00, -1.1322e+01,  3.1702e-02,
       -1.0255e+00, -3.0870e+00, -3.7327e+00,  5.3875e-01,  3.5679e+00,
        6.9276e+00,  1.5793e+00,  5.1188e-01,  3.1868e+00,  6.1534e+00,
       -4.8941e+00, -2.9959e-01, -3.6276e+00,  2.3825e+00, -1.4402e+00,
       -4.7577e+00,  4.3607e+00, -4.9814e+00, -3.6672e+00, -1.8052e+00,
       -2.1888e+00, -4.2875e+00,  5.5712e+00, -5.2875e+00, -1.8346e+00,
       -2.2015e+00, -7.7091e-01, -4.8260e+00,  1.2464e+00, -1.7945e+00,
       -8.1280e+00,  1.9994e+00,  1.1413e+00,  3.8032e+00, -2.8783e+00,
       -4.2136e-01, -4.4177e+00,  7.7456e+00,  4.9535e+00,  1.7402e+00,
        1.8275e-01,  2.4218e+00, -3.1496e+00, -3.8057e-02, -2.9818e+00,
        8.3396e-01,  1.1531e+01,  3.5684e+00,  2.5970e+00, -2.8438e+00,
        3.2755e+00,  4.5674e+00,  3.2219e+00,  3.4206e+00,  1.1200e-01,
        1.0303e-01, -5.8396e+00,  4.6370e-01,  2.7750e+00, -5.3713e+00,
       -5.0247e+00, -2.0212e+00,  5.8772e-01,  1.1569e+00,  1.32

In [39]:
doc[3].vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [40]:
base_token=nlp("sandwich")
base_token.vector.shape

(300,)

In [41]:
doc=nlp("bread cat tomato super man burger pizza")
for token in doc:
  print(f"{token.text}<->{base_token.text}:",token.similarity(base_token))

bread<->sandwich: 0.6341067177397708
cat<->sandwich: 0.21172844406069505
tomato<->sandwich: 0.563211340796867
super<->sandwich: 0.29403969918362954
man<->sandwich: 0.11603198603413611
burger<->sandwich: 0.7900927756758959
pizza<->sandwich: 0.7681410380841011


In [42]:
def similar_words(base_word,word_to_compare):
  base_token=nlp(base_word)
  doc=nlp(word_to_compare)
  for token in doc:

   if (token.similarity(base_token))>0.50:
      print(token.text)


In [43]:
similar_words("cat","tiger man burger shop cream animal pet")

tiger
animal
pet


In [44]:
#cosine similarity
king=nlp.vocab["king"].vector
man=nlp.vocab["man"].vector
women=nlp.vocab["women"].vector
queen=nlp.vocab["queen"].vector

In [45]:
result=king-man+women

In [46]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([result],[queen])

array([[0.36506233]], dtype=float32)

In [47]:
!pip install kaggle
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

mv: cannot stat 'kaggle.json': No such file or directory


In [48]:
!kaggle datasets download -d jillanisofttech/fake-or-real-news

fake-or-real-news.zip: Skipping, found more recently modified local copy (use --force to force download)


In [49]:
!unzip /content/fake-or-real-news.zip

Archive:  /content/fake-or-real-news.zip
replace fake_or_real_news.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: fake_or_real_news.csv   


In [50]:
df=pd.read_csv("/content/fake_or_real_news.csv")

In [51]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [52]:
df['label'].value_counts()

REAL    3171
FAKE    3164
Name: label, dtype: int64

In [53]:
df['label_num']=df['label'].map(
   {
       'FAKE':0,
       'REAL':1
   }

)

In [54]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  label_num  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL          1  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE          0  
4  It's primary day in New York and front-runners...  REAL          1

In [55]:
!python -m spacy download en_core_web_lg
import spacy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.3 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [63]:
nlp = spacy.load("en_core_web_lg")

In [64]:
df['vector'] = df['text'].apply(lambda text: nlp(text).vector)

In [65]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  label_num  \
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0   
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0   
2  U.S. Secretary of State John F. Kerry said Mon...  REAL          1   
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE          0   
4  It's primary day in New York and front-runners...  REAL          1   

                                              vector  
0  [-1.3751823, 1.3421849, -2.3666484, 0.12908486...  
1  [-1.7449774, 0.93961924, -2.024867, 0.42536643...  
2  [-1.9426425, 1.0062195, -1.9992222, 0.20469022...  
3  [-1.9125352, -0.1481846, -1.1432766, 0.6861217...  
4  [-1.8516092, 1.3163909, -2.1726575, 1.2286776,...

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.vector.values, df.label_num, test_size=0.20, random_state=42)

In [67]:
import numpy as np

In [70]:
X_train.shape

(5068,)

In [69]:
x_train_stack=np.stack(X_train)
x_test_stack=np.stack(X_test)

In [71]:
x_train_stack.shape

(5068, 300)

In [75]:
x_test_stack.shape

(1267, 300)

In [76]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [77]:
x_train_stack=scaler.fit_transform(x_train_stack)
x_test_stack=scaler.fit_transform(x_test_stack)



In [72]:
from sklearn.naive_bayes import MultinomialNB

In [73]:
model=MultinomialNB()

In [78]:
model.fit(x_train_stack,y_train)

MultinomialNB()

In [82]:
y_pred=model.predict(x_test_stack)

In [81]:
from sklearn.metrics import confusion_matrix

In [83]:
print(confusion_matrix(y_pred,y_test))

[[539 207]
 [ 89 432]]


In [84]:
from sklearn.metrics import accuracy_score

In [85]:
print(accuracy_score(y_pred,y_test))

0.7663772691397001
